/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toRganizado;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.ArrayList;
//import java.sql.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {



public static void main(String[] args) {
    
    
    ProjectController projectController =  new ProjectController();
    Project project = new Project();
    
    project.setId();
    project.setName("Novo nome do Projeto");
    project.setDescription("Descrição");
    projectController.update(project);
    
    List<Project> projects = projectController.getAll();
    System.out.println("Total de projetos" +  projects.size());
    
    projectController.removeById(1);
     
    
    TaskController taskController =  new TaskController();
    Task task = new Task();
    
    task.setIdProject(1);
    task.setName("Criar as telas de aplicação");
    task.setDescription("Devem ser criadas telas para os cadastros");
       task.setNotes("Sem Notas");
       task.setIsCompleted(false);
        task.setDeadline(new Date());
        
        taskController.save(task);
        
        task.setName("Alterar telas da aplicação");
        taskController.update(task);
        List<Task> tasks = taskController.getAll(1);
        System.out.println("Total de tarefas = " + tasks.size());
}

}
       
               
   